AppMetrics/AppMetrics

- sandbox/App.Metrics.Sandbox/Controllers/ExceptionThrowingController.cs
- sandbox/App.Metrics.Sandbox/JustForTesting/SampleRequests.cs
- src/App.Metrics.Extensions.Middleware/ErrorRequestMeterMiddleware.cs
This change adds a try catch around the middleware so that we catch unhandled exceptions and log them as 500 internal server errors.
> Logging unhandled exceptions as 500 errors

- README.md
- ~I have successfully run a [local build](https://github.com/alhardy/AppMetrics#how-to-build)~
- ~I have included unit tests for the issue/feature~
- ~I have included the github issue number in my commits~
> fix references to xUnit.net

- benchmarks/App.Metrics.Benchmarks/App.Metrics.Benchmarks.csproj
- src/App.Metrics/App.Metrics.csproj
- test/App.Metrics.Facts/App.Metrics.Facts.csproj
I like to use App.Metrics in one of my libraries but I don't want to have Microsoft.Extensions.Logging in my dependency tree.
Libraries should only depend on `Microsoft.Extensions.Logging.Abstractions` which contains the necessary interfaces for creating log entries (ILoggerFactory, ILogger, etc). `Microsoft.Extensions.Logging` is Microsoft's *implementation* and should only be referenced by applications.
PS: I hope it's ok to not create a separate issue for this... I'll create it if you want it.
App.Metrics now references the Abstractions package; the test-projects reference the actual Logging package (because they need to call `AddLogging()`).
NOTE: Technically, this is a "breaking change" because *applications* who use your library and don't have a reference to …
> Reference Microsoft.Extensions.Logging.Abstractions instead of full Logging package

- build.cake
The build script is extremely slow because every project is restored and built separately. The new dotnet cli supports restoring and building a *.sln.
* dotnet restore is just called once for the whole solution
* dotnet build is just called once for the whole solution on windows. Non-Windows still uses the old logic due to the multi-targeting issue.
> Build Script: Restore the whole solution; build the whole solution on windows

- test/App.Metrics.Extensions.Middleware.Integration.Facts/DependencyInjection/TestConfiguration/appsettings.json
#123
A simple workaround.
This should probably be reverted when the bug is fixed. However, it seems like this will not be before ASP.NET Core 2.0
> #123 config tests fail for cultures with different number formats

- src/App.Metrics/Health/Extensions/HealthCheckFactoryExtensions.cs
- test/App.Metrics.Facts/Health/HealthCheckFactoryExtensionsTests.cs
#172 
Add an optional boolean parameter (degradedOnError) to all the health check extension methods of the class `HealthCheckFactoryExtensions`.
Thus when a health check fails we can not only return an **Unhealthy** status but also a **Degraded** one.
I also unit tested all extensions methods of the class for **Unhealthy** and **Degraded** status.
> #172 Add degradedOnError param to all health check extensions methods

- src/App.Metrics.Extensions.Middleware/Extensions/HttpContextExtensions.cs
This fix addresses issue #191, adding a quick dictionary check and returning the default value if the item does not exist in the dictionary (instead of throwing a `KeyNotFoundException`).
Normally it appears AppMetrics endpoints append some custom items to the `HttpContext` dictionary items, which are then referred to later. If for some reason the dictionary items are blank, a default value is returned.
In the scenario where somehow the dictionary item is not appended in the first place, the code was throwing a `KeyNotFoundException`. With this bugfix, the code now checks for the existence of the dictionary item first, and returns the same default value if it is missing.
> Bugfix: Check for Metrics Route in HttpContext.

- src/App.Metrics.Abstractions/MetricTags.cs
- src/App.Metrics.Core/Internal/DefaultMetricContextRegistry.cs
- test/App.Metrics.Facts/Filtering/MetricsContextFilteringTests.cs
- test/App.Metrics.Facts/Filtering/MetricsFilteringTests.cs
- Issue #235 
- Fixed issue when tags for options not included in metricName when trying to use it without explicitly provided tags.
> Fix issue #235

- src/App.Metrics.Abstractions/App.Metrics.Abstractions.csproj
- src/App.Metrics.Core/App.Metrics.Core.csproj
Issue #245.
This changes the App.Metrics.Abstractions package to target both .NET Standard and .NET Framework in order to reduce the number of dependencies installed in framework projects.
> #245 Target .NET 4.5 on App.Metrics.Abstractions

- src/App.Metrics.Core/ReservoirSampling/ExponentialDecay/DefaultForwardDecayingReservoir.cs
- test/App.Metrics.Sampling.Facts/ExponentiallyDecayingReservoirTests.cs
https://github.com/AppMetrics/AppMetrics/issues/256
Ensured that the sum is updated during rescaling, and also added verification for it in the relevant unit test. 
Also included a couple minor performance tweaks.
> Exponential decay reservoir should update sum during rescaling

- src/App.Metrics.Core/Scheduling/DefaultMeterTickerScheduler.cs
[294](https://github.com/AppMetrics/AppMetrics/issues/294)
Fix spelling mistake in logs in the word 'Scheduler'
> #294 fix spelling in logs

- build/dependencies.props
- src/App.Metrics.Core/App.Metrics.Core.csproj
- src/App.Metrics.Core/App_Packages/LibLog.g.cs
Merged changes from LibLog before it was split into multiple files. See also https://github.com/damianh/LibLog/pull/145
- Removed unnecessary RegEx when using NLog
- Removed unnecessary StackTrace capture when using NLog
- Reduced memory allocations when using Log4net
> LibLog - Fixed NLog + Log4net callsite. Added support for NLog structured logging

- src/App.Metrics.Abstractions/Meter/MeterOptions.cs
- test/App.Metrics.Facts/Meter/MeterOptionsTests.cs
#364
Sets the default value of the `MeterOptions.ReportSetItems` property to `true`. This matches the XML documentation comments and the behaviour of the `CounterOptions.ReportSetItems` property.
> #364 - Fixes MeterOptions.ReportSetItems default value.

- src/Reporting/src/App.Metrics.Reporting.InfluxDB/Client/DefaultLineProtocolClient.cs
- src/Reporting/test/App.Metrics.Reporting.InfluxDB.Facts/DefaultLineProtocolClientTests.cs
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/alhardy/AppMetrics/blob/master/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
- #414 
- Reset `_failureAttempts` variable when `response.IsSuccessStatusCode`
> #414 reset failure attempts in case of successful call to influxdb

- src/Health/src/App.Metrics.Health.Checks.Http/HttpGetHealthCheckBuilderExtensions.cs
- src/Health/src/App.Metrics.Health.Checks.Http/HttpPostHealthCheckBuilderExtensions.cs
- [AddHttpPostCheck Extension](https://github.com/AppMetrics/AppMetrics/issues/430)
- Added an extension that allow me to provide `HttpContent` and or `Headers` (via means of a a Dictionary). This is needed to perform health checks against secured endpoints. This is a 1-to-1 copy of the previous implementation of the HttpCheck, BUT with added parameters to the functions to allow the setting of `Headers` and `HttpContent`
- I've not tested / ran this code within the context of this specific solution, but it is running on my staging env within my own code base. (I figured I'd provide it back to App.Metrics... If you're happy with the minimum implementation as is. I'm open to refactoring at a later stage if needed/suggested. (To reduce shared commonalities between the 2 extensions) 
~I have …
> AddHttpPostCheck Extension

- src/Reporting/src/App.Metrics.Reporting.Http/Client/DefaultHttpClient.cs
- src/Reporting/src/App.Metrics.Reporting.Http/Client/HttpSettings.cs
- src/Reporting/test/App.Metrics.Reporting.Http.Facts/MetricsHttpReporterBuilderTests.cs
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/master/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
https://github.com/AppMetrics/AppMetrics/issues/455
- I have a case where i am reporting metrics via http/https which we have secured with JWT auth (Authorization header with token value). There doesn't seem to be a way to attach a token with header to the http object, as it relates to app metrics. What i've done is this exact op.
> added auth header options

- src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/Extensions/MetricDataValueSourceExtensions.cs
#474
Change the metric family type for counters and histograms
> fix(prometheus): label counters and histograms correctly

- src/Reporting/src/App.Metrics.Formatters.Prometheus/App.Metrics.Formatters.Prometheus.csproj
- src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/AsciiFormatter.cs
https://github.com/AppMetrics/AppMetrics/issues/396
```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.Dispose(Boolean disposing)
at System.IO.TextWriter.Dispose()
at App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter.Write(Stream destination, IEnumerable`1 metrics, NewLineFormat newLine)
at App.Metrics.Formatters.Prometheus.MetricsPrometheusTextOutputFormatter.WriteAsync(Stream output, MetricsDataValueSource metricsData, CancellationToken cancellationToken)
```
Should call `IAsyncDisposable.DisposeAsync` when …
> Use await using for .NET Standard 2.1

- src/Reporting/src/App.Metrics.Formatters.Prometheus/Internal/AsciiFormatter.cs
- #520
.NET Core 3.0 block sync operations by default. I've changed the implementation of App.Metrics.Formatters.Prometheus.Internal.AsciiFormatter to use async all the way down. 
` I've branched from features/4.0.0 where the fix was already started`
> AsciiFormatter use async all the way down (#520)

- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/ActiveRequestCounterEndpointMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/ApdexMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/OAuthTrackingMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/PerRequestTimerMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/RequestTimerMiddleware.cs
- src/AspNetCore/test/App.Metrics.AspNetCore.Tracking.Facts/Middleware/RequestTimerMiddlewareTests.cs
#468 
The referenced issue highlights a problem with the ASPNET Core middlewares. If an exception is thrown further down the pipeline, AppMetrics is not handling it. Therefore, timers are left running and counters become inaccurate. 
This PR adds a finally block to all tracking ASPNET Core middlewares to ensure timers are stopped, counters are decremented, and logging is completed. There is a test fixture for the middleware mentioned in the issue. I ran out of time to copy it for the others.
I did run the code clean up using the supplied profile, but it mostly changed code I hadn't touched. Therefore, I'll leave it up to someone else.
> Handle exceptions in ASPNET Core tracking middleware

- src/Core/src/App.Metrics.Abstractions/Timer/IMeasureTimerMetrics.cs
- src/Core/src/App.Metrics.Core/Timer/DefaultTimerManager.cs
- src/Core/test/App.Metrics.Facts/Managers/DefaultTimerManagerTests.cs
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/master/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
#304 
This one should be self explanatory, I would like to record timers with a user supplied values.
> Add ability to record a timer using a user supplied value. Fixes #304

- build/shared.props
- global.json
- src/AspNetCore/src/App.Metrics.AspNetCore.Mvc.Core/App.Metrics.AspNetCore.Mvc.Core.csproj
- src/AspNetCore/src/App.Metrics.AspNetCore.Mvc.Core/MvcRouteTemplateResolver.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Mvc/App.Metrics.AspNetCore.Mvc.csproj
- src/Directory.Build.targets
Fixes #550.
* Change relevant libraries to multi-target netcoreapp3.1
* Implements workaround alluded to in #519 since it did not _compile_ for netcoreapp3.1
> GH550: Add netcoreapp3.1 target framework

- src/Core/benchmarks/App.Metrics.Benchmarks/BenchmarkDotNetBenchmarks/Metrics/DefaultMetricContextRegistryBenchmark.cs
- src/Core/benchmarks/App.Metrics.Benchmarks/Fixtures/MetricContextTestFixture.cs
- src/Core/src/App.Metrics.Abstractions/ContextualMetricTagProviders.cs
- src/Core/src/App.Metrics.Abstractions/MetricsOptions.cs
- src/Core/src/App.Metrics.Core/Builder/MetricsBuilder.cs
- src/Core/src/App.Metrics.Core/Internal/DefaultMetricContextRegistry.cs
- src/Core/src/App.Metrics.Core/Internal/Extensions/MetricsOptionsExtensions.cs
- src/Core/src/App.Metrics.Core/Internal/KeyValuePairMetricsOptions.cs
- Adding contextual tags for all metrics (resolving #334)
- Add contextual tags to MetricsOptions in a very similar manner to global tags, but with computed values (Func<string>) instead of string values
- There were no tests for GlobalMetricTags so I didn't add any new ones
> Contextual tags

- src/AspNetCore/src/App.Metrics.AspNetCore.Core/Internal/Extensions/MetricsExtensions.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Core/Internal/HttpRequestMetricsRegistry.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/ActiveRequestCounterEndpointMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/ApdexMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/PerRequestTimerMiddleware.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Middleware/RequestTimerMiddleware.cs
- src/AspNetCore/test/App.Metrics.AspNetCore.Tracking.Facts/Middleware/ActiveRequestCounterEndpointMiddlewareTests.cs
- src/AspNetCore/test/App.Metrics.AspNetCore.Tracking.Facts/Middleware/RequestTimerMiddlewareTests.cs
Filter web socket requests from timer and APDEX middleware.
Count active web sockets in a separate counter.
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/master/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
Fixes #545 
Apologies for the delay since saying I'd do this.
The middleware now uses IsWebSocketRequest to keep different metrics for web sockets, which are usually very long lived transactions. Primarily request timers ignore web sockets and active web socket requests are tracked in a separate counter.
The IsWebSocketRequest flag is only correct if the WebSocketMiddleware has already executed in …
> Add behaviour to ASP.NET Core middleware when IsWebSocketRequests.

- src/AspNetCore/src/App.Metrics.AspNetCore.Hosting/MetricsAspNetHostBuilderExtensions.cs
- Addressing issue #559: I need to use the method ConfigureMetrices and it doesn't exist for IWebHostBuilder as it exists for IHostBuilder only.
- I have added the required extensions for IWebHostBuilder
> Add webhost and host builder extensions

- src/AspNetCore/src/App.Metrics.AspNetCore.Endpoints/Builder/MetricsAspNetEndpointHostBuilderExtensions.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Tracking/Builder/MetricsAspNetTrackingHostBuilderExtensions.cs
- src/AspNetCore/src/App.Metrics.AspNetCore/DefaultMetricsAspNetHostBuilderExtensions.cs
#562 IWebHostBuilder does not contain a definition for 'UseMetrics'.
The 'UseMetrics' extension exists only for IHostBuilder.
added the following extensions for 'IWebHostBuider'
--MetricsAspNetEndpoint
--MetricsAspNetTracking
--DefaultMetricsAspNet
> #562 add use metrics extensions for IWebHostBuider

- src/AspNetCore/src/App.Metrics.AspNetCore.Endpoints/Builder/MetricsAspNetEndpointHostBuilderExtensions.cs
- src/AspNetCore/src/App.Metrics.AspNetCore.Endpoints/Builder/MetricsAspNetEndpointWebHostBuilderExtensions.cs
This PR allows for serving the metrics to a custom port, but removes the automatic configuration of the host as described in #497
> #497 Allow metrics on custom port with custom host configuration

- src/Extensions/src/App.Metrics.AppNetCore/App.Metrics.AppNetCore.csproj
- src/Extensions/src/App.Metrics.Extensions.Hosting/App.Metrics.Extensions.Hosting.csproj
As discussed in #611 this PR fixes the issue with the hosting project. I noticed that App.Metrics.AppNetCore also has the same issue, so fixed that while I was at it.
> Fix netstandard2.0 project references

- src/Extensions/src/App.Metrics.Extensions.Collectors/HostedServices/SystemUsageCollectorHostedService.cs
Fixed #639 
Added the _process.Refresh(); call to refresh the stats of the process before it's being set,
> Fixed system usage stats not being updated

- src/Reporting/sandbox/MetricsStatsDSandbox/Host.cs
- src/Reporting/sandbox/MetricsStatsDSandboxMvc/Program.cs
- src/Reporting/src/App.Metrics.Reporting.StatsD/StatsDReporterBuilder.cs
In order to make the StatsD reporter consistent with other App.Metrics reporters, move the reporter into the default App.Metrics.Reporting.SttasD interface.
> moved StatsDBuilder into main StatsD namespace

- src/Core/src/App.Metrics.Abstractions/Formatters/IMetricsChunkedOutputFormatter.cs
- src/Reporting/src/App.Metrics.Formatting.StatsD/Internal/StatsDPointSampler.cs
- src/Reporting/src/App.Metrics.Formatting.StatsD/MetricSnapshotStatsDStringWriter.cs
- src/Reporting/src/App.Metrics.Formatting.StatsD/MetricsStatsDStringOutputFormatter.cs
- src/Reporting/src/App.Metrics.Reporting.Socket/Client/DefaultSocketClient.cs
- src/Reporting/src/App.Metrics.Reporting.Socket/Client/SocketSettings.cs
- src/Reporting/src/App.Metrics.Reporting.Socket/SocketMetricsReporter.cs
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/main/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
- #650
- Add a way for formatters to return pieces of serialized packets of metrics data instead of a single write to the stream. This can be used to split the data sent to the aggregator server by the transport layer.
> Add chunked output for formatters for UDP datagram output

- README.md
The current link from the README page returns a 404 not found page on Github. Hopefully this correct that.
- [Issue #665](https://github.com/AppMetrics/AppMetrics/issues/665)
- Just updating the link to reference the CONTRIBUTING.md file in .github directory
> #665 Correcting link to contribution guidelines

- src/Reporting/src/App.Metrics.Formatting.StatsD/Internal/StatsDPointSampler.cs
- src/Reporting/src/App.Metrics.Formatting.StatsD/Internal/StatsDSyntax.cs
- src/Reporting/test/App.Metrics.Reporting.StatsD.Facts/MetricSnapshotDogStatsDStringSerializerTest.cs
- src/Reporting/test/App.Metrics.Reporting.StatsD.Facts/MetricSnapshotStatsDStringSerializerTest.cs
Before submitting a pull request, please have a quick read through the [contribution guidelines](https://github.com/AppMetrics/AppMetrics/blob/main/.github/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`
- #668
- We're emulating what DogStatsD is doing by converting `Meter` into the closest metric we have to DataDog `Rate` metric, which is the `Count` metric in AppMetrics and StatsD.
> Convert AppMetrics Meter to StatsD Count

- src/Extensions/src/App.Metrics.Extensions.Hosting/MetricsReporterBackgroundService.cs
- src/Extensions/src/App.Metrics.Extensions.Hosting/ServiceCollectionMetricsReportingExtensions.cs
#659
I have a CronJob which may start and stop very quickly. Some metrics are generated but as a result of how short lived the application is, the metrics are never sent. After debugging the issue I have concluded that the reason for this is because the reporter is running as a background worker which is essentially cancelled before it can even start. Furthermore due to the way the hosted application works, the TaskFactory never completes once the application is shutting down.
This change uses the `IHostApplicationLifetime` service to detect the `ApplicationStopping` signal and flushes the remaining metrics one last time before the application is fully stopped.
**_Notes:_**
* The build was broken already on a vanilla checkout but the project I edited was building and continues to build …
> Stop and flush on host shutdown

- src/Concurrency/src/App.Metrics.Concurrency/App.Metrics.Concurrency.csproj
- No linked issue
- Current version (4.2.0) of App.Metrics.Concurrency package contains netstandart1.1 library that requires tons of dependencies. I see no reason to support netstd1.1, but legacy. I've just added netstandart2.0 target framework to remove all deps.
> App.Metrics.Concurrency support netstandart2.0.
